//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AerLingus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JourneySegment
    {
        public string couponNo { get; set; }
        public Nullable<System.DateTime> departureDate { get; set; }
        public string origin { get; set; }
        public string destination { get; set; }
        public int ID { get; set; }
        public string TicketNo { get; set; }
        public Nullable<int> IDFR { get; set; }
    
        public virtual Flight_Records Flight_Records { get; set; }
    }
}
